### ISSUE TITLE
Game not moving forward rounds

### ISSUE THREAD

**Issue by LilMudX** [RavingSmurfGB/Py_AutoBloons#1]
Obyn gets placed first round gets played, Monkey Sub placed, doesn't move forward round, then tried to upgrade Monkey Sub

**Comment by RavingSmurfGB** [comment]
Hey,

Apologies for not getting back to you sooner,

**Comment by RavingSmurfGB** [comment]
Hey, 

Apologies for not comming back to you sooner, I am a bit here and there with this project.
But am happy to get this working with you if you are still interested.

To understand the issue more could you let me know your resolution, number of monitors, the config options (if any was changed) and a screenshot of the issue please!

**Comment by F0X3Z** [comment]
Hi! I have an issue, the bot fails to do the 00X upgrades
My resolution is 2560x1440 both in windows and in BTD6 fullscreen.
I have two monitors.

Basically this is what the bot does:
Places Obyn
Places Sub
Upgrades Sub to 100
Fails to upgrade sub only clicks on the sub and then again to "unclick it"
Fails the upgrade again
Upgrades Sub to 200
Places Ninja
Upgrades Ninja to 100
Upgrades Ninja to 200
Fails upgrade on Ninja
Upgrades Ninja to 300
Fails upgrade on Sub
dead

Config: 
XP_Monkey:
Logging: True
Gameplan_file: 2.csv
Auto_Hero_Select: False
[game_log.txt](https://github.com/RavingSmurfGB/Py_AutoBloons/files/9464263/game_log.txt)

Thanks in advance and thanks for updating it again! :)
