### ISSUE TITLE
can't install requirements

### ISSUE THREAD

**Issue by HoriexMizuki** [RavingSmurfGB/Py_AutoBloons#6]
when i try to install them this show up
![image](https://github.com/RavingSmurfGB/Py_AutoBloons/assets/147771781/ba32f574-d00c-4f77-8961-df1d7fdfccb4)

**Comment by RavingSmurfGB** [comment]
hmm okay, what it the line you entered in the console there?
Did you type python on or before that line?

**Comment by HoriexMizuki** [comment]
how to do it

**Comment by RavingSmurfGB** [comment]
if you dont understand my questions thats fine, but I need more to work with here.

**Comment by HoriexMizuki** [comment]
like what

**Comment by HoriexMizuki** [comment]
i got it thanks
